# Supervised Model : Classification - Practice

In [7]:
# libraries
import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [8]:
# import dataset
df = pd.read_csv('../Dataset/bankloan.csv')
df

     age  ed  employ  address  income  debtinc   creddebt   othdebt  default
0     41   3      17       12     176      9.3  11.359392  5.008608        1
1     27   1      10        6      31     17.3   1.362202  4.000798        0
2     40   1      15       14      55      5.5   0.856075  2.168925        0
3     41   1      15       14     120      2.9   2.658720  0.821280        0
4     24   2       2        0      28     17.3   1.787436  3.056564        1
..   ...  ..     ...      ...     ...      ...        ...       ...      ...
695   36   2       6       15      27      4.6   0.262062  0.979938        1
696   29   2       6        4      21     11.5   0.369495  2.045505        0
697   33   1      15        3      32      7.6   0.491264  1.940736        0
698   45   1      19       22      77      8.4   2.302608  4.165392        0
699   37   1      12       14      44     14.7   2.994684  3.473316        0

[700 rows x 9 columns]

In [9]:
# make X and y
x = sm.add_constant(df[['employ','debtinc','creddebt','othdebt']])
y = df['default']
display(x,y)

     const  employ  debtinc   creddebt   othdebt
0      1.0      17      9.3  11.359392  5.008608
1      1.0      10     17.3   1.362202  4.000798
2      1.0      15      5.5   0.856075  2.168925
3      1.0      15      2.9   2.658720  0.821280
4      1.0       2     17.3   1.787436  3.056564
..     ...     ...      ...        ...       ...
695    1.0       6      4.6   0.262062  0.979938
696    1.0       6     11.5   0.369495  2.045505
697    1.0      15      7.6   0.491264  1.940736
698    1.0      19      8.4   2.302608  4.165392
699    1.0      12     14.7   2.994684  3.473316

[700 rows x 5 columns]

0      1
1      0
2      0
3      0
4      1
      ..
695    1
696    0
697    0
698    0
699    0
Name: default, Length: 700, dtype: int64

In [10]:
# model fitting
sm_logit = sm.Logit(y,x)
result = sm_logit.fit()

Optimization terminated successfully.
         Current function value: 0.411165
         Iterations 7

In [11]:
print(result.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:                default   No. Observations:                  700
Model:                          Logit   Df Residuals:                      695
Method:                           MLE   Df Model:                            4
Date:                Thu, 30 May 2024   Pseudo R-squ.:                  0.2844
Time:                        14:55:15   Log-Likelihood:                -287.82
converged:                       True   LL-Null:                       -402.18
Covariance Type:            nonrobust   LLR p-value:                 2.473e-48
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.2302      0.236     -5.210      0.000      -1.693      -0.767
employ        -0.2436      0.029     -8.456      0.000      -0.300      -0.187
debtinc        0.0885      0.021      4.200      0.000       0.047       0.130
creddebt       0.5041      0.083      6.094      0.000       0.342       0.666
othdebt       -0.0040      0.053     -0.076      0.940      -0.107       0.099
==============================================================================

In [12]:
def calc_vif(X):

    # Calculating VIF
    vif = pd.DataFrame()
    vif["variables"] = X.columns
    vif["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

    return(vif)

In [13]:
# collinearity check
calc_vif(df[['employ','debtinc','creddebt','othdebt']])

  variables       VIF
0    employ  2.222753
1   debtinc  3.045977
2  creddebt  2.816577
3   othdebt  4.116876

In [14]:
 # Model interpretation
x.describe().loc[['min','max']].T

               min       max
const     1.000000   1.00000
employ    0.000000  31.00000
debtinc   0.400000  41.30000
creddebt  0.011696  20.56131
othdebt   0.045584  27.03360

In [35]:

# Parameter Estimate
# OR ~ Odd Ratio
# employment tenure
B1 = -0.2436
c = 25
d = 24
OR1 = np.exp(B1*(c-d))
OR1
# between 0 years - 31 years employment tenure, when employment tenure increase by 1 year and no changes in another variable,
# the risk to become default most likely increase by 0.7838010920039364 times.

0.7838010920039364

In [27]:
m = 1/OR1
m
# the risk to become default most likely decrease by 1.2758338948511925 times.

3.380420128015566

In [17]:
# debt ratio against income
B2 = 0.0885
c = 0.42
d = 0.41
OR2 = np.exp(B2*(c-d))
OR2
# between 0.4 % - 41.3 % debt ratio to income, when the ratio increase by 1% and no change in another variable,
# the risk to become defult most likely increase by 1.0008853917280514 % times.

1.0008853917280514

In [18]:
# credit amount
B3 = 0.5041
c = 10
d = 5
OR3 = np.exp(B3*(c-d))
OR3
# between 0.01 $ - 20.56 $ credit amount, when the credit amount increase by 5 $ and no change in another variable,
# the risk to become defauult most likekly increase by 12.434812515742879 times.

12.434812515742879

LLR-TEST:

B1, B2, B3, B4: P-value of the log-likelyhood-ratio (2.473e-48) is below than 0.05. we can say we have enough evidence that either employ, debtinc, creditdebt, othdebt have significant effect to credit default rate.

WALD-TEST:
<br>
1. B0: P-value of the partial test is below than 0.05. means, B0 needed for the model
1. B1: P-value of the partial test is below than 0.05. means, we have enough evidence that employ decrease the default rate
1. B2: P-value of the partial test is below than 0.05. means, we have enough evidence that debtinc increase the default rate
1. B3: P-value of the partial test is below than 0.05. means, we have enough evidence that creditdebt increase the default rate
1. B4: P-value of the partial test is more than 0.05. means, we DON'T have enough evidence that othdebt has significant effect with default rate

COEFFICIENT DETERMINATION:

Pseudo R-Square: 28.44 %, this model can explain 28.44 $ variation of default rate.

In [19]:
x

     const  employ  debtinc   creddebt   othdebt
0      1.0      17      9.3  11.359392  5.008608
1      1.0      10     17.3   1.362202  4.000798
2      1.0      15      5.5   0.856075  2.168925
3      1.0      15      2.9   2.658720  0.821280
4      1.0       2     17.3   1.787436  3.056564
..     ...     ...      ...        ...       ...
695    1.0       6      4.6   0.262062  0.979938
696    1.0       6     11.5   0.369495  2.045505
697    1.0      15      7.6   0.491264  1.940736
698    1.0      19      8.4   2.302608  4.165392
699    1.0      12     14.7   2.994684  3.473316

[700 rows x 5 columns]

In [20]:
# SKLEARN ! -> feature selection
x_train, x_test, y_train, y_test = train_test_split(
x,
y,
stratify=y, # make even for 0 and 1 between train and test
test_size=0.3,
random_state=2024
)

In [21]:
# check the target value proportion
display(y_train.value_counts(normalize=True),y_test.value_counts(normalize=True))

default
0    0.738776
1    0.261224
Name: proportion, dtype: float64

default
0    0.738095
1    0.261905
Name: proportion, dtype: float64

In [22]:
# model fitting
sm_logit_train = sm.Logit(y_train,x_train)
result_train = sm_logit_train.fit()

Optimization terminated successfully.
         Current function value: 0.405553
         Iterations 7

In [23]:
# predict using the model (result_train)
y_predict_proba = result_train.predict(x_test)
y_predict_proba

685    0.345999
37     0.207462
213    0.153759
136    0.457627
345    0.655833
         ...
421    0.008731
436    0.252531
452    0.176158
17     0.003316
509    0.007379
Length: 210, dtype: float64

In [24]:
# convert proba into class (0 and 1)
y_predict_class = np.where(y_predict_proba>0.5,1,0)
y_predict_class

array([0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
# accuracy
print('model accuracy:',accuracy_score(y_test,y_predict_class))

model accuracy: 0.8047619047619048

In [26]:
# confusion_matrix
confusion_matrix(y_test,y_predict_class)

array([[144,  11],
       [ 30,  25]], dtype=int64)

guessing 0 but the actual 0 = 144 (correct)

guessing 1 but the actual 0 = 30 (wrong)

guessing 0 but the actual 1 = 11 (wrong)

guessing 1 but the actual 1 = 25 (correct)

accuracy: (144 + 25) / 144 + 30 + 11 + 25 = 0.80476