In [1]:
import pandas as pd

In [2]:
df =  pd.read_csv('lrfm_df.csv')
df.head()

,Unnamed: 0,customer_unique_id,Length,Recency,Frequency,Monetary,cluster
0,0,0000366f3b9a7992bf8c76cfdf3221e2,160,160,1,141.90,0
1,1,0000b849f77a49e4a4ce2b2a4ca5be3f,163,163,1,27.19,0
2,2,0000f46a3911fa3c0805444483337064,585,585,1,86.22,2
3,3,0000f6ccb0745a6a4b88665a16c9f078,369,369,1,43.62,2
4,4,0004aac84e0df4da2b147fca70cf8255,336,336,1,196.89,2

In [3]:
df_2 = pd.read_csv('new_customer_df1.csv')
df_2.head()

,customer_id,customer_unique_id_x,zip_code_prefix,customer_city,customer_state,Recency,Frequency,Monetary,cluster,customers_geolocation_lat,customers_geolocation_lng
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,519,1,146.87,2,-20.509898,-47.397866
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,277,1,335.48,0,-23.726853,-46.545746
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,151,1,157.73,0,-23.527788,-46.660310
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,218,1,173.30,0,-23.496930,-46.185352
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,80,1,252.25,0,-22.987222,-47.151073

In [4]:
df_2.rename(columns={'customer_unique_id_x':'customer_unique_id'},inplace=True)
df_2.columns

Index(['customer_id', 'customer_unique_id', 'zip_code_prefix', 'customer_city',
       'customer_state', 'Recency', 'Frequency', 'Monetary', 'cluster',
       'customers_geolocation_lat', 'customers_geolocation_lng'],
      dtype='object')

In [6]:
df_l = df[['customer_unique_id','Length']]
df_l

                     customer_unique_id  Length
0      0000366f3b9a7992bf8c76cfdf3221e2     160
1      0000b849f77a49e4a4ce2b2a4ca5be3f     163
2      0000f46a3911fa3c0805444483337064     585
3      0000f6ccb0745a6a4b88665a16c9f078     369
4      0004aac84e0df4da2b147fca70cf8255     336
...                                 ...     ...
96088  fffcf5a5ff07b0908bd4e2dbc735a684     495
96089  fffea47cd6d3cc0a88bd621562a9d061     310
96090  ffff371b4d645b6ecea244b27531430a     617
96091  ffff5962728ec6157033ef9805bacc48     168
96092  ffffd2657e2aad2907e67c3e9daecbeb     532

[96093 rows x 2 columns]

In [7]:
df_merge = pd.merge(df_2,df_l,on='customer_unique_id',how='left')
df_merge

,customer_id,customer_unique_id,zip_code_prefix,customer_city,customer_state,Recency,Frequency,Monetary,cluster,customers_geolocation_lat,customers_geolocation_lng,Length
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,519,1,146.87,2,-20.509898,-47.397866,519.0
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,277,1,335.48,0,-23.726853,-46.545746,277.0
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,151,1,157.73,0,-23.527788,-46.660310,151.0
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,218,1,173.30,0,-23.496930,-46.185352,218.0
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,80,1,252.25,0,-22.987222,-47.151073,80.0
...,...,...,...,...,...,...,...,...,...,...,...,...
118440,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP,193,1,88.78,0,-23.587901,-46.501830,193.0
118441,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP,196,1,129.06,0,-23.612294,-46.765787,196.0
118442,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE,191,1,56.04,0,-3.744128,-38.510859,191.0
118443,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS,347,1,711.07,1,-29.956391,-51.167614,347.0
118444,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP,302,1,21.77,0,-23.593985,-46.910591,302.0

In [9]:
df_merge.to_csv('new_customer_df2.csv',index=False)